main: com.rifledluffy.chairs.RFChairs
name: RFChairs
version: 6.0
authors: [Rifle D. Luffy, VicenteRD, carlpoole, i0xHeX]
api-version: 1.13
description: Chairs but Rifle's way.
softdepend: [WorldGuard, WorldEdit]
commands:
  rfchairs:
    usage: /<command>
    description: The main prefix for other commands. Type /rfchairs help for more info
    aliases: [rfc]
permissions:
  rfchairs.use:
    description: Use of chairs
    default: true
  rfchairs.break:
    description: allows users to break chairs
    default: true
  rfchairs.mute:
    description: allows the messages when events are triggered
    default: true
  rfchairs.toggle:
    description: allows the toggling of seating on chairs for a player
    default: true
  rfchairs.priority:
    description: allows the priority removal of other players from chairs
    default: op
  rfchairs.manage:
    description: allows players to manage the plugin
    default: op
  rfchairs.reload:
    description: reload the chairs plugin
    default: op
  rfchairs.reset:
    description: reset all chairs
    default: op
  rfchairs.*:
    description: Wildcard Perm
    default: op
    children:
      rfchairs.reload: true
      rfchairs.reset: true
      rfchairs.manage: true
      rfchairs.use: true